version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./data/neo4j:/data
      - ./data/logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: